### ISSUE TITLE
Capture and report all `logging` calls from ck2yaml

### ISSUE THREAD

**Issue by rwest** [comocheng/ChemCheck#14]
ck2yaml uses the logging module. There should be a way to capture all its messages, and report them.

**Comment by 12Chao** [comment]
Please check pull request #28.

**Comment by bryanwweber** [comment]
Please wait for the pull request to be merged before closing the issue 😊 you can even put in the pull request description "Closes #12345" and GitHub will automatically close that issue when the pull request is merged!

**Comment by 12Chao** [comment]
Thanks for the instruction :thumbsup:! I will do so next time.

**Comment by rwest** [comment]
We can come back and think of better ways to do this, eg. that don't need us to modify the ck2yaml.py file, and/or that write to a buffer in memory instead of a file on disk, but for now this is at least functioning, so I'm closing the issue.
