### ISSUE TITLE
UnicodeDecodeErrors should be handled properly

### ISSUE THREAD

**Issue by bryanwweber** [comocheng/ChemCheck#23]
The following line throws an unhandled exception when the mechanism file is loaded for editing (click the "Edit" link after uploading):

```
!REF: HONG ET AL. PROC. OF THE COMB. INST. 33 (2011) 309�316
```

That byte in the middle cannot be decoded by UTF-8 because it is actually a Windows 1252 (CP1252) encoded en-dash. The loader should be able to gracefully fail over to another encoding if necessary.

The workaround that ck2yaml uses is here:

https://github.com/Cantera/cantera/blob/674c37ce3cbfd867179d8ab6c9af605b5d56eb6c/interfaces/cython/cantera/ck2yaml.py#L1338-L1342

It ignores any errors and then strips out any non-ASCII characters.

**Comment by rwest** [comment]
The ACE editor view now handles this with
```python
    with open(f, 'r', errors='ignore') as file_content:
        content = strip_nonascii(file_content.read())
```
but it's not been implemented everywhere yet.

**Comment by rwest** [comment]
One option would be to implement this *as* you are uploading the files.

**Comment by bryanwweber** [comment]
I'm not sure that stripping non-ASCII as a default is the best default. I believe Python includes a library to guess encodings, or we could try a few common ones before giving up and stripping all the offending characters.

**Comment by bryanwweber** [comment]
I should clarify that I mean that last comment specifically as it applies to the editor interface. Let's leave ck2yaml as-is for now.

**Comment by bryanwweber** [comment]
@12Chao has this issue been resolved?

**Comment by 12Chao** [comment]
Sorry for the late response, I just got my github account recoverd. I believe it just uses `strip_nonascii` to strip out the special characters.

**Comment by bryanwweber** [comment]
No problem! Should this issue be closed?

**Comment by 12Chao** [comment]
Yes, I'll close it.
