### ISSUE TITLE
Update the README with instructions to run the site locally

### ISSUE THREAD

**Issue by bryanwweber** [comocheng/ChemCheck#3]
Hi @12Chao Can you update the README with how to run the site locally? Also with a `pipfile.lock` or something similar to create an environment. Thank you!

**Comment by bryanwweber** [comment]
Oh, I see you have a pipfile already, perfect.

**Comment by rwest** [comment]
Closed (sort of) by 8879eaecd15c8645167aff87bc67311854974a5c, although the README could certainly be improved further.
